### ISSUE TITLE
500 error when saving a task

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#613]
reproducible on midas-dev.18f.us, here's what I see in the log when it happens:

```
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)
    at TCP.onread (/var/www/midas/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31)

Details:  error: invalid input syntax for type timestamp with time zone: ""
```

**Comment by dhcole** [comment]
Verified on production:
```
Request URL:https://midas.18f.us/api/task/36
Request Method:PUT
Status Code:200 OK
```

**Comment by ultrasaurus** [comment]
resolved
