### ISSUE TITLE
Error when saving tasks in 0.7.0

### ISSUE THREAD

**Issue by dhcole** [18F/midas#956]
Reported by @GailSwanson, when saving a task the server returns `POST http://localhost:1337/api/task 500 (Internal Server Error)` with the following in the log:

```
error: Sending 500 ("Server Error") response: 
 Error (E_UNKNOWN) :: Encountered an unexpected error
error: invalid input syntax for type timestamp with time zone: ""
    at Connection.parseE (/Users/davidcole/dev/midas/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:534:11)
    at Connection.parseMessage (/Users/davidcole/dev/midas/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:361:17)
    at Socket.<anonymous> (/Users/davidcole/dev/midas/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)

Details:  error: invalid input syntax for type timestamp with time zone: ""
```

**Comment by awhig** [comment]
If you leave the Estimated Completion date field blank, you get this error.

**Comment by jeremiak** [comment]
Yup, thanks @awhig! I'm fixing this up in the `bug/task-creation` branch and just waiting for some more feedback from @GailSwanson to make sure that we cover all the bases
